import { Injectable, signal } from '@angular/core';

export type Lang = 'en' | 'ru' | 'kk';

const T: Record<Lang, Record<string, string>> = {
  en: {
    'nav.menu': 'Menu', 'nav.cart': 'Cart', 'nav.orders': 'Orders', 'nav.saved': 'Saved', 'nav.profile': 'Profile',
    'auth.tagline': 'Your coffee, your way', 'auth.welcomeBack': 'Welcome back', 'auth.signInSubtitle': 'Sign in to continue ordering',
    'auth.mobileNumber': 'Mobile Number', 'auth.pin': '4-Digit PIN', 'auth.signIn': 'Sign In', 'auth.newHere': 'New here?',
    'auth.createAccount': 'Create Account', 'auth.createYourAccount': 'Create your account', 'auth.getStarted': 'Get started',
    'auth.setupDesc': 'Set up your account in seconds', 'auth.firstName': 'First Name', 'auth.lastName': 'Last Name',
    'auth.choosePin': 'Choose 4-Digit PIN', 'auth.confirmPin': 'Confirm PIN', 'auth.haveAccount': 'Have an account?',
    'greeting.morning': 'Good morning', 'greeting.afternoon': 'Good afternoon', 'greeting.evening': 'Good evening',
    'menu.change': 'Change', 'menu.search': 'Search coffee, food...', 'menu.orderAgain': 'Order Again', 'menu.add': '+ Add',
    'menu.all': 'All', 'menu.nothingFound': 'Nothing found', 'menu.tryDifferent': 'Try a different search',
    'menu.viewCart': 'View Cart', 'menu.customise': 'Customise your order', 'menu.free': 'Free', 'menu.addToCart': 'Add to Cart',
    'menu.specials': "Today's Specials", 'menu.reorder': 'Reorder', 'menu.addIcon': '+ Add',
    'item.details': 'Item Details', 'item.quantity': 'Quantity', 'item.notFound': 'Item not found', 'item.add': 'Add', 'item.toCart': 'to Cart',
    'item.customize': 'Customize', 'item.chooseOne': 'choose one', 'item.addToCart': 'Add to Cart',
    'cart.title': 'Your Cart', 'cart.empty': 'Your cart is empty', 'cart.emptyDesc': 'Add items from the menu to get started',
    'cart.browseMenu': 'Browse Menu', 'cart.addNote': '+ add note', 'cart.hideNote': '− hide note',
    'cart.notePlaceholder': 'e.g. extra hot, no lid…', 'cart.subtotal': 'Subtotal', 'cart.total': 'Total', 'cart.placeOrder': 'Place Order',
    'fav.title': 'Saved Items', 'fav.subtitle': 'Your favorite menu items', 'fav.empty': 'No saved items yet',
    'fav.emptyHint': 'Tap ♥ on any item to save it here', 'fav.addToCart': '+ Add to Cart',
    'loc.title': 'Choose Location', 'loc.subtitle': 'Where would you like to order from?',
    'loc.noLocations': 'No locations available', 'loc.checkLater': 'Please check back later', 'loc.continue': 'Continue to Menu →',
    'orders.title': 'My Orders', 'orders.tabActive': 'Active', 'orders.tabHistory': 'History', 'orders.tabDeclined': 'Declined',
    'orders.noOrders': 'No orders yet', 'orders.ordersHere': 'Your orders will appear here', 'orders.total': 'Total',
    'order.details': 'Order Details', 'order.timeline': 'Order Timeline', 'order.live': 'Live',
    'order.items': 'Items', 'order.total': 'Total', 'order.payment': 'Payment', 'order.status': 'Status', 'order.method': 'Method',
    'order.payKaspi': 'Pay with Kaspi', 'order.creatingInvoice': 'Creating invoice...', 'order.scanQR': 'Scan this QR code with the Kaspi app',
    'order.viewReceipt': 'View Receipt', 'order.receipt': 'Receipt', 'order.thankYou': 'Thank you for your order!',
    'order.readyIn': 'Ready in approx.', 'order.min': 'min', 'order.declined': 'Declined:', 'order.nowArrow': '← Now', 'order.subtotal': 'Subtotal',
    'timeline.Created': 'Order Placed', 'timeline.Accepted': 'Accepted by café', 'timeline.Preparing': 'Preparing your order',
    'timeline.Ready': 'Ready for Pickup!', 'timeline.Completed': 'Completed',
    'status.Created': 'Order Placed', 'status.Accepted': 'Accepted', 'status.Preparing': 'Preparing',
    'status.Ready': 'Ready for Pickup', 'status.Completed': 'Completed', 'status.Declined': 'Declined',
    'profile.title': 'Profile', 'profile.edit': '✏️ Edit', 'profile.editTitle': 'Edit Profile',
    'profile.save': 'Save', 'profile.cancel': 'Cancel', 'profile.myOrders': 'My Orders', 'profile.viewHistory': 'View order history',
    'profile.savedItems': 'Saved Items', 'profile.favSubtitle': 'Your favorite menu items', 'profile.lifeStats': 'Lifetime Stats',
    'profile.orders': 'Orders', 'profile.totalSpent': 'Total Spent (₸)', 'profile.settings': 'Settings',
    'profile.phone': 'Phone Number', 'profile.notifications': 'Notifications', 'profile.notifSubtitle': 'Order status alerts',
    'profile.changePin': 'Change PIN', 'profile.changePinDesc': 'Update your 4-digit PIN', 'profile.currentPin': 'Current PIN',
    'profile.newPin': 'New PIN', 'profile.updatePin': 'Update PIN', 'profile.signOut': 'Sign Out',
    'profile.dangerZone': 'Danger Zone', 'profile.deleteAccount': 'Delete Account',
    'profile.deleteConfirm': 'Are you sure? This cannot be undone.', 'profile.delete': 'Delete', 'profile.deleting': 'Deleting…',
    'profile.memberSince': 'Member since', 'profile.language': 'Language', 'profile.firstName': 'First Name', 'profile.lastName': 'Last Name',
  },
  ru: {
    'nav.menu': 'Меню', 'nav.cart': 'Корзина', 'nav.orders': 'Заказы', 'nav.saved': 'Избранное', 'nav.profile': 'Профиль',
    'auth.tagline': 'Ваш кофе, ваш выбор', 'auth.welcomeBack': 'С возвращением', 'auth.signInSubtitle': 'Войдите, чтобы продолжить',
    'auth.mobileNumber': 'Номер телефона', 'auth.pin': '4-значный PIN', 'auth.signIn': 'Войти', 'auth.newHere': 'Впервые здесь?',
    'auth.createAccount': 'Создать аккаунт', 'auth.createYourAccount': 'Создайте аккаунт', 'auth.getStarted': 'Начните здесь',
    'auth.setupDesc': 'Настройте аккаунт за секунды', 'auth.firstName': 'Имя', 'auth.lastName': 'Фамилия',
    'auth.choosePin': 'Выберите 4-значный PIN', 'auth.confirmPin': 'Подтвердите PIN', 'auth.haveAccount': 'Уже есть аккаунт?',
    'greeting.morning': 'Доброе утро', 'greeting.afternoon': 'Добрый день', 'greeting.evening': 'Добрый вечер',
    'menu.change': 'Изменить', 'menu.search': 'Поиск кофе, еды...', 'menu.orderAgain': 'Повторить заказ', 'menu.add': '+ Добавить',
    'menu.all': 'Все', 'menu.nothingFound': 'Ничего не найдено', 'menu.tryDifferent': 'Попробуйте другой запрос',
    'menu.viewCart': 'Корзина', 'menu.customise': 'Настройте заказ', 'menu.free': 'Бесплатно', 'menu.addToCart': 'В корзину',
    'menu.specials': 'Акции дня', 'menu.reorder': 'Повторить', 'menu.addIcon': '+ Добавить',
    'item.details': 'Детали товара', 'item.quantity': 'Количество', 'item.notFound': 'Товар не найден', 'item.add': 'Добавить', 'item.toCart': 'в корзину',
    'item.customize': 'Настройте', 'item.chooseOne': 'выберите один', 'item.addToCart': 'В корзину',
    'cart.title': 'Ваша корзина', 'cart.empty': 'Корзина пуста', 'cart.emptyDesc': 'Добавьте товары из меню',
    'cart.browseMenu': 'В меню', 'cart.addNote': '+ заметка', 'cart.hideNote': '− скрыть',
    'cart.notePlaceholder': 'Напр. очень горячий, без крышки…', 'cart.subtotal': 'Подытог', 'cart.total': 'Итого', 'cart.placeOrder': 'Оформить заказ',
    'fav.title': 'Избранное', 'fav.subtitle': 'Ваши любимые товары', 'fav.empty': 'Нет сохранённых товаров',
    'fav.emptyHint': 'Нажмите ♥ на товар, чтобы сохранить', 'fav.addToCart': '+ В корзину',
    'loc.title': 'Выбрать локацию', 'loc.subtitle': 'Откуда вы хотите заказать?',
    'loc.noLocations': 'Нет доступных локаций', 'loc.checkLater': 'Проверьте позже', 'loc.continue': 'В меню →',
    'orders.title': 'Мои заказы', 'orders.tabActive': 'Активные', 'orders.tabHistory': 'История', 'orders.tabDeclined': 'Отклонённые',
    'orders.noOrders': 'Заказов нет', 'orders.ordersHere': 'Ваши заказы появятся здесь', 'orders.total': 'Итого',
    'order.details': 'Детали заказа', 'order.timeline': 'Хронология заказа', 'order.live': 'В эфире',
    'order.items': 'Товары', 'order.total': 'Итого', 'order.payment': 'Оплата', 'order.status': 'Статус', 'order.method': 'Метод',
    'order.payKaspi': 'Оплатить через Kaspi', 'order.creatingInvoice': 'Создание счёта...', 'order.scanQR': 'Отсканируйте QR-код в приложении Kaspi',
    'order.viewReceipt': 'Чек', 'order.receipt': 'Чек', 'order.thankYou': 'Спасибо за заказ!',
    'order.readyIn': 'Готов примерно через', 'order.min': 'мин', 'order.declined': 'Отклонён:', 'order.nowArrow': '← Сейчас', 'order.subtotal': 'Подытог',
    'timeline.Created': 'Заказ принят', 'timeline.Accepted': 'Принят кафе', 'timeline.Preparing': 'Готовится',
    'timeline.Ready': 'Готов к выдаче!', 'timeline.Completed': 'Завершён',
    'status.Created': 'Заказ принят', 'status.Accepted': 'Подтверждён', 'status.Preparing': 'Готовится',
    'status.Ready': 'Готов к выдаче', 'status.Completed': 'Завершён', 'status.Declined': 'Отклонён',
    'profile.title': 'Профиль', 'profile.edit': '✏️ Изменить', 'profile.editTitle': 'Редактировать профиль',
    'profile.save': 'Сохранить', 'profile.cancel': 'Отмена', 'profile.myOrders': 'Мои заказы', 'profile.viewHistory': 'История заказов',
    'profile.savedItems': 'Избранное', 'profile.favSubtitle': 'Ваши любимые товары', 'profile.lifeStats': 'Статистика',
    'profile.orders': 'Заказы', 'profile.totalSpent': 'Всего потрачено (₸)', 'profile.settings': 'Настройки',
    'profile.phone': 'Номер телефона', 'profile.notifications': 'Уведомления', 'profile.notifSubtitle': 'Обновления статуса заказа',
    'profile.changePin': 'Изменить PIN', 'profile.changePinDesc': 'Обновите ваш PIN', 'profile.currentPin': 'Текущий PIN',
    'profile.newPin': 'Новый PIN', 'profile.updatePin': 'Обновить PIN', 'profile.signOut': 'Выйти',
    'profile.dangerZone': 'Опасная зона', 'profile.deleteAccount': 'Удалить аккаунт',
    'profile.deleteConfirm': 'Вы уверены? Это нельзя отменить.', 'profile.delete': 'Удалить', 'profile.deleting': 'Удаление…',
    'profile.memberSince': 'Участник с', 'profile.language': 'Язык', 'profile.firstName': 'Имя', 'profile.lastName': 'Фамилия',
  },
  kk: {
    'nav.menu': 'Мәзір', 'nav.cart': 'Себет', 'nav.orders': 'Тапсырыстар', 'nav.saved': 'Сақталған', 'nav.profile': 'Профиль',
    'auth.tagline': 'Сіздің кофеңіз', 'auth.welcomeBack': 'Қош келдіңіз', 'auth.signInSubtitle': 'Жалғастыру үшін кіріңіз',
    'auth.mobileNumber': 'Телефон нөмірі', 'auth.pin': '4 таңбалы PIN', 'auth.signIn': 'Кіру', 'auth.newHere': 'Жаңа пайдаланушы?',
    'auth.createAccount': 'Тіркелу', 'auth.createYourAccount': 'Тіркелгі жасаңыз', 'auth.getStarted': 'Бастаңыз',
    'auth.setupDesc': 'Бірнеше секундта тіркелу', 'auth.firstName': 'Аты', 'auth.lastName': 'Тегі',
    'auth.choosePin': '4 таңбалы PIN таңдаңыз', 'auth.confirmPin': 'PIN растаңыз', 'auth.haveAccount': 'Тіркелгіңіз бар ма?',
    'greeting.morning': 'Қайырлы таң', 'greeting.afternoon': 'Қайырлы күн', 'greeting.evening': 'Қайырлы кеш',
    'menu.change': 'Өзгерту', 'menu.search': 'Кофе, тағам іздеу...', 'menu.orderAgain': 'Қайта тапсырыс', 'menu.add': '+ Қосу',
    'menu.all': 'Барлығы', 'menu.nothingFound': 'Ештеңе табылмады', 'menu.tryDifferent': 'Басқа сөзбен іздеңіз',
    'menu.viewCart': 'Себет', 'menu.customise': 'Тапсырысты баптаңыз', 'menu.free': 'Тегін', 'menu.addToCart': 'Себетке қосу',
    'menu.specials': 'Күндік ұсыныстар', 'menu.reorder': 'Қайта тапсыру', 'menu.addIcon': '+ Қосу',
    'item.details': 'Тауар туралы', 'item.quantity': 'Саны', 'item.notFound': 'Тауар табылмады', 'item.add': 'Қосу', 'item.toCart': 'себетке',
    'item.customize': 'Баптаңыз', 'item.chooseOne': 'бірін таңдаңыз', 'item.addToCart': 'Себетке қосу',
    'cart.title': 'Себетіңіз', 'cart.empty': 'Себет бос', 'cart.emptyDesc': 'Мәзірден тауар қосыңыз',
    'cart.browseMenu': 'Мәзірге өту', 'cart.addNote': '+ ескерту', 'cart.hideNote': '− жасыру',
    'cart.notePlaceholder': 'Мыс. өте ыстық, қақпақсыз…', 'cart.subtotal': 'Аралық сома', 'cart.total': 'Жиыны', 'cart.placeOrder': 'Тапсырыс беру',
    'fav.title': 'Сақталған', 'fav.subtitle': 'Сүйікті тауарларыңыз', 'fav.empty': 'Сақталған тауар жоқ',
    'fav.emptyHint': 'Сақтау үшін ♥ түймесін басыңыз', 'fav.addToCart': '+ Себетке',
    'loc.title': 'Орынды таңдаңыз', 'loc.subtitle': 'Қайдан тапсырыс бергіңіз келеді?',
    'loc.noLocations': 'Қол жетімді орын жоқ', 'loc.checkLater': 'Кейінірек тексеріңіз', 'loc.continue': 'Мәзірге өту →',
    'orders.title': 'Тапсырыстарым', 'orders.tabActive': 'Белсенді', 'orders.tabHistory': 'Тарих', 'orders.tabDeclined': 'Қабылданбаған',
    'orders.noOrders': 'Тапсырыс жоқ', 'orders.ordersHere': 'Тапсырыстарыңыз осында', 'orders.total': 'Жиыны',
    'order.details': 'Тапсырыс мәліметтері', 'order.timeline': 'Тапсырыс хронологиясы', 'order.live': 'Тікелей',
    'order.items': 'Тауарлар', 'order.total': 'Жиыны', 'order.payment': 'Төлем', 'order.status': 'Күй', 'order.method': 'Әдіс',
    'order.payKaspi': 'Kaspi арқылы төлеу', 'order.creatingInvoice': 'Шот жасалуда...', 'order.scanQR': 'Kaspi-де QR кодты сканерлеңіз',
    'order.viewReceipt': 'Чек', 'order.receipt': 'Чек', 'order.thankYou': 'Тапсырысыңыз үшін рахмет!',
    'order.readyIn': 'Шамамен дайын болады', 'order.min': 'мин', 'order.declined': 'Қабылданбады:', 'order.nowArrow': '← Қазір', 'order.subtotal': 'Аралық',
    'timeline.Created': 'Тапсырыс берілді', 'timeline.Accepted': 'Кафе қабылдады', 'timeline.Preparing': 'Дайындалуда',
    'timeline.Ready': 'Дайын!', 'timeline.Completed': 'Аяқталды',
    'status.Created': 'Тапсырыс берілді', 'status.Accepted': 'Қабылданды', 'status.Preparing': 'Дайындалуда',
    'status.Ready': 'Дайын', 'status.Completed': 'Аяқталды', 'status.Declined': 'Қабылданбады',
    'profile.title': 'Профиль', 'profile.edit': '✏️ Өңдеу', 'profile.editTitle': 'Профильді өңдеу',
    'profile.save': 'Сақтау', 'profile.cancel': 'Болдырмау', 'profile.myOrders': 'Тапсырыстарым', 'profile.viewHistory': 'Тапсырыстар тарихы',
    'profile.savedItems': 'Сақталған', 'profile.favSubtitle': 'Сүйікті тауарлар', 'profile.lifeStats': 'Жалпы статистика',
    'profile.orders': 'Тапсырыстар', 'profile.totalSpent': 'Жалпы жұмсалған (₸)', 'profile.settings': 'Параметрлер',
    'profile.phone': 'Телефон нөмірі', 'profile.notifications': 'Хабарландырулар', 'profile.notifSubtitle': 'Тапсырыс күйі туралы',
    'profile.changePin': 'PIN өзгерту', 'profile.changePinDesc': 'PIN жаңартыңыз', 'profile.currentPin': 'Ағымдағы PIN',
    'profile.newPin': 'Жаңа PIN', 'profile.updatePin': 'PIN жаңарту', 'profile.signOut': 'Шығу',
    'profile.dangerZone': 'Қауіпті аймақ', 'profile.deleteAccount': 'Тіркелгіні жою',
    'profile.deleteConfirm': 'Сенімдісіз бе? Болдырмау мүмкін емес.', 'profile.delete': 'Жою', 'profile.deleting': 'Жою…',
    'profile.memberSince': 'Мүше болды', 'profile.language': 'Тіл', 'profile.firstName': 'Аты', 'profile.lastName': 'Тегі',
  },
};

@Injectable({ providedIn: 'root' })
export class LangService {
  private readonly KEY = 'yurt_lang';
  readonly lang = signal<Lang>((localStorage.getItem('yurt_lang') as Lang) || 'ru');

  setLang(lang: Lang): void {
    this.lang.set(lang);
    localStorage.setItem(this.KEY, lang);
  }

  t(key: string): string {
    return T[this.lang()][key] ?? key;
  }
}
